apiVersion: v1
kind: ReplicationController
metadata:
  name: nextreportapprc
spec:
  replicas: 3
  selector:
    app: nextreportapp
  template:
    metadata:
      name: nextreportapppod
      labels:
       app: nextreportapp
    spec:
      containers:
      - name: nextreportappcontainer
        image: nagarjunacse/next-report-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nextreportappsvc
spec:
  type: NodePort
  selector:
    app: nextreportapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
...
